# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_newspaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='newspaper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Newspaper'),
            preserve_default=False,
        ),
    ]
